import {Box,Typography,Chip,Card,Stack,Button,Alert,Skeleton,Table,TableHead,TableRow,TableCell,TableBody,TableContainer} from '@mui/material';
import {ArrowForwardRounded,CheckCircleRounded,HourglassTopRounded,ErrorOutlineRounded,InboxOutlined} from '@mui/icons-material';
import {useNavigate} from 'react-router-dom';
import type {ReactNode} from 'react';
import type {Run,Validation} from '../types';
import {timeLabel,dateLabel} from '../api';
export function PageHeading({eyebrow='LIQUIDITY MANAGEMENT',title,subtitle,action}:{eyebrow?:string;title:string;subtitle:string;action?:ReactNode}){return <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" alignItems={{xs:'stretch',sm:'center'}} gap={2} mb={3}><Box><Typography sx={{fontSize:10,fontWeight:700,letterSpacing:1.6,color:'primary.main',mb:1}}>{eyebrow}</Typography><Typography variant="h4">{title}</Typography><Typography variant="body2" color="text.secondary" mt={.8}>{subtitle}</Typography></Box>{action}</Stack>;}
export function SectionHead({title,subtitle,action}:{title:string;subtitle?:string;action?:ReactNode}){return <Stack direction="row" justifyContent="space-between" alignItems="center" p={2.5} gap={1}><Box><Typography variant="h6">{title}</Typography>{subtitle&&<Typography variant="caption" color="text.secondary">{subtitle}</Typography>}</Box>{action}</Stack>;}
export function Status({status}:{status:string}){const good=status==='completed',partial=status==='completed_with_exceptions',pending=['queued','running'].includes(status);return <Chip size="small" icon={good?<CheckCircleRounded/>:pending?<HourglassTopRounded/>:<ErrorOutlineRounded/>} label={{completed:'Completed',completed_with_exceptions:'With exceptions',queued:'Queued',running:'Calculating',failed_validation:'Validation failed',failed:'Failed',interrupted:'Interrupted'}[status]||status} sx={{bgcolor:good?'#E7F5EF':pending?'#EBF0FF':partial?'#FFF3DF':'#FCEBEC',color:good?'#168466':pending?'#315DD7':partial?'#A46F22':'#BA4B50','& .MuiChip-icon':{color:'inherit',fontSize:14}}}/>;}
export function Loading(){return <Stack gap={2}><Skeleton height={70}/><Stack direction="row" gap={2}>{[1,2,3].map(i=><Skeleton key={i} variant="rounded" width="33%" height={125}/>)}</Stack><Skeleton variant="rounded" height={330}/></Stack>;}
export function Empty({title,description,action}:{title:string;description:string;action?:ReactNode}){return <Card sx={{p:6,textAlign:'center'}}><Box sx={{display:'inline-flex',p:2,bgcolor:'#EEF3FC',borderRadius:3,color:'primary.main',mb:2}}><InboxOutlined fontSize="large"/></Box><Typography variant="h6">{title}</Typography><Typography variant="body2" color="text.secondary" sx={{maxWidth:430,mx:'auto',my:1.5}}>{description}</Typography>{action}</Card>;}
export function ErrorMessage({error}:{error:unknown}){return error?<Alert severity="error" sx={{mb:2}}>{error instanceof Error?error.message:String(error)}</Alert>:null;}
export function RunTable({runs,limit=50}:{runs:Run[];limit?:number}){const nav=useNavigate();return <TableContainer><Table><TableHead><TableRow><TableCell>Calculation</TableCell><TableCell>Reporting date</TableCell><TableCell>Status</TableCell><TableCell>Created</TableCell><TableCell/></TableRow></TableHead><TableBody>{runs.slice(0,limit).map(r=><TableRow hover key={r.id}><TableCell><Typography sx={{fontSize:12,fontWeight:600}}>Contractual baseline</Typography><Typography variant="caption" color="text.secondary">{r.id.slice(0,8)} · {r.entity_name}</Typography></TableCell><TableCell>{dateLabel(r.as_of_date)}</TableCell><TableCell><Status status={r.status}/></TableCell><TableCell sx={{whiteSpace:'nowrap'}}>{timeLabel(r.created)}</TableCell><TableCell align="right"><Button size="small" endIcon={<ArrowForwardRounded/>} onClick={()=>nav(`/results/${r.id}`)}>Open</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer>;}
export function Exceptions({validation}:{validation:Validation}){return <Stack gap={1.5}>{validation.rejected_count===0?<Alert severity="success">All {validation.accepted_count} contracts passed the supported calculation rules.</Alert>:<><Alert severity="warning">{validation.rejected_count} contracts will be excluded. Results will cover accepted contracts only.</Alert>{validation.exceptions.map((e,i)=><Box key={i} sx={{p:2,border:'1px solid #EBDCD0',borderRadius:2,bgcolor:'#FFFCF8'}}><Typography variant="subtitle2">{e.contract_id} <Typography component="span" variant="caption" color="text.secondary">· row {e.row}</Typography></Typography><Typography variant="body2" color="text.secondary">{e.error}</Typography></Box>)}</>}</Stack>;}
