import {useState} from 'react';
import {Dialog,DialogTitle,DialogContent,DialogActions,TextField,Button,Box,MenuItem,Alert,FormControlLabel,Switch,Typography} from '@mui/material';
import type {Contract} from '../types';
import {productLabel} from '../api';
export default function ContractEditor({contract,onClose,onSave,existingIds=[]}:{existingIds?:string[];contract:Contract;onClose:()=>void;onSave:(c:Contract)=>void}){
 const [c,set]=useState<Contract>({...contract});const [error,setError]=useState('');const undated=c.product==='demand_deposit'||c.product==='cash_central_bank';
 function field(key:keyof Contract,label:string,options?:string[],type='text'){return <TextField size="small" fullWidth label={label} value={c[key]??''} type={type} select={!!options} onChange={e=>set({...c,[key]:key==='frequency_months'?Number(e.target.value):e.target.value})} slotProps={type==='date'?{inputLabel:{shrink:true}}:undefined}>{options?.map(v=><MenuItem key={v} value={v}>{key==='product'?productLabel(v):v.replaceAll('_',' ')}</MenuItem>)}</TextField>;}
 const save=()=>{if(existingIds.includes(c.contract_id)){setError('This contract ID already exists in the entity.');return;}if(!/^[A-Za-z0-9_.-]{1,64}$/.test(c.contract_id)){setError('Use a unique contract ID with letters, numbers, hyphens or underscores.');return;}if(!Number.isFinite(Number(c.principal))||Number(c.principal)<=0){setError('Enter a positive principal balance.');return;}let value=c;if(undated)value={contract_id:c.contract_id,product:c.product,currency:c.currency,principal:c.principal};else if(!c.next_payment||!c.maturity||!c.accrual_start){setError('Complete the payment and accrual dates.');return;}onSave(value);};
 return <Dialog open onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>Contract details<Typography variant="body2" color="text.secondary">Changes are saved to this entity’s portfolio after you click Save portfolio.</Typography></DialogTitle><DialogContent><Box sx={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:2,pt:1}}>{field('contract_id','Contract ID')}{field('product','Product',['loan','term_deposit','bond','interbank_asset','cash_central_bank','borrowing','demand_deposit'])}{field('currency','Currency',['JOD','USD','EUR','GBP'])}{field('principal','Outstanding principal')}{!undated&&<>{field('annual_rate',c.rate_type==='floating'?'Current all-in rate · decimal':'Annual rate · decimal (0.06 = 6%)')}{field('rate_type','Rate type',['fixed','floating'])}{c.rate_type==='floating'&&<><TextField size="small" fullWidth label="Rate index" value={c.interest_rate_index??''} onChange={e=>set({...c,interest_rate_index:e.target.value})} helperText="Required when using a forward curve"/>{field('client_rate_spread','Contractual margin · decimal')} {field('rate_floor','Rate floor · optional')} {field('rate_cap','Rate cap · optional')}</>}{field('repayment','Repayment',['bullet','equal_principal','level_payment'])}{field('day_count','Day count',['ACT/365F','ACT/360','30E/360'])}{field('frequency_months','Frequency · months',['1','3','6','12'])}{field('accrual_start','Accrual start',undefined,'date')}{field('next_payment','Next payment',undefined,'date')}{field('maturity','Maturity',undefined,'date')}<FormControlLabel sx={{gridColumn:'1/-1'}} control={<Switch checked={!!c.end_of_month} onChange={e=>set({...c,end_of_month:e.target.checked})}/>} label={<Typography variant="body2">Align payments to month end</Typography>}/></>}</Box>{undated&&<Alert severity="info" sx={{mt:2}}>{c.product==='cash_central_bank'?'This balance is separately disclosed as counterbalancing capacity.':'This balance is disclosed separately. No withdrawal date or interest schedule is invented.'}</Alert>}{error&&<Alert severity="error" sx={{mt:2}}>{error}</Alert>}</DialogContent><DialogActions sx={{p:2.5}}><Button onClick={onClose}>Cancel</Button><Button variant="contained" onClick={save}>Apply changes</Button></DialogActions></Dialog>;
}
