import {useState} from 'react';
import {Alert,Box,Card,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,Typography} from '@mui/material';
import {KeyboardArrowDownRounded,KeyboardArrowRightRounded} from '@mui/icons-material';
import type {NsfrReport,NsfrRow} from '../types';
import {money} from '../api';

const sections:Record<string,string>={asf:'Available stable funding',rsf:'Required stable funding',result:'Net stable funding ratio'};
const amount=(value:string,currency:string)=>value===''?'—':money(value,currency);
export default function NsfrReportTable({report}:{report:NsfrReport}){
 const [open,setOpen]=useState<Record<string,boolean>>({});const groups=[...new Set(report.rows.map(row=>row.section))];
 return <Card><Box sx={{px:{xs:2,md:3},py:2.25,borderBottom:'1px solid',borderColor:'divider'}}><Typography variant="h6">NSFR Report</Typography><Typography variant="body2" color="text.secondary" mt={.4}>Maturity and currency structure follows the supplied NSFR report format. Select a section to show its source lines.</Typography></Box><TableContainer sx={{maxHeight:'66vh'}}><Table size="small" sx={{minWidth:1260}}><TableHead><TableRow><TableCell sx={{minWidth:70,fontWeight:700}}>Code</TableCell><TableCell sx={{minWidth:350,fontWeight:700}}>NSFR exposure</TableCell><TableCell align="right">JOD &lt;6m</TableCell><TableCell align="right">JOD 6m–1y</TableCell><TableCell align="right">JOD ≥1y</TableCell><TableCell align="right">USD</TableCell><TableCell align="right">Other CCY</TableCell><TableCell align="right">Weighted amount</TableCell></TableRow></TableHead><TableBody>{groups.map(section=>{const rows=report.rows.filter(row=>row.section===section),expanded=!!open[section],summary=rows.find(row=>row.kind==='subtotal'||row.kind==='ratio')||rows[0],shown=expanded?rows:[summary];return <><TableRow key={`${section}-header`} hover onClick={()=>setOpen(value=>({...value,[section]:!expanded}))} sx={{cursor:'pointer',bgcolor:'#EEF5F4'}}><TableCell colSpan={2} sx={{fontWeight:700}}>{expanded?<KeyboardArrowDownRounded fontSize="small" sx={{verticalAlign:'middle',mr:.75}}/>:<KeyboardArrowRightRounded fontSize="small" sx={{verticalAlign:'middle',mr:.75}}/>}{sections[section]}</TableCell><TableCell colSpan={5}/><TableCell align="right" sx={{fontWeight:750,color:section==='result'?(Number(summary.weighted)>=1?'success.main':'error.main'):undefined}}>{section==='result'?`${(Number(summary.weighted)*100).toFixed(2)}%`:amount(summary.weighted,report.currency)}</TableCell></TableRow>{shown.map(row=>row===summary&&!expanded?null:<Row key={`${section}-${row.code}-${row.label}`} row={row} currency={report.currency}/>)}</>})}</TableBody></Table></TableContainer><Alert severity="info" sx={{m:2.5}}>{report.basis}</Alert></Card>;
}
function Row({row,currency}:{row:NsfrRow;currency:string}){const subtotal=row.kind==='subtotal'||row.kind==='ratio';return <TableRow sx={{bgcolor:subtotal?'#EAF3F1':'#fff'}}><TableCell>{row.code}</TableCell><TableCell sx={{fontWeight:subtotal?700:400}}>{row.label}</TableCell><TableCell align="right">{amount(row.jod[0],currency)}</TableCell><TableCell align="right">{amount(row.jod[1],currency)}</TableCell><TableCell align="right">{amount(row.jod[2],currency)}</TableCell><TableCell align="right">{amount(String(row.usd.reduce((sum,value)=>sum+Number(value||0),0)),currency)}</TableCell><TableCell align="right">{amount(String(row.other.reduce((sum,value)=>sum+Number(value||0),0)),currency)}</TableCell><TableCell align="right" sx={{fontWeight:subtotal?700:400,color:row.kind==='ratio'?(Number(row.weighted)>=1?'success.main':'error.main'):undefined}}>{row.kind==='ratio'?`${(Number(row.weighted)*100).toFixed(2)}%`:amount(row.weighted,currency)}</TableCell></TableRow>}
