# Generated by Django 5.2.17 on 2026-09-16 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_exceptions', 'Completed with exceptions'), ('failed_validation', 'Failed validation'), ('failed', 'Failed'), ('interrupted', 'Interrupted')], db_index=True, default='queued', max_length=32)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('entity', models.CharField(max_length=64)),
                ('as_of_date', models.DateField()),
                ('engine_version', models.CharField(max_length=32)),
                ('input_payload', models.JSONField()),
                ('input_hash', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('result_summary', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('contract_id', models.CharField(max_length=64)),
                ('product', models.CharField(max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('direction', models.CharField(max_length=8)),
                ('payment_date', models.DateField()),
                ('accrual_start', models.DateField()),
                ('accrual_end', models.DateField()),
                ('days_from_asof', models.PositiveIntegerField()),
                ('principal', models.DecimalField(decimal_places=3, max_digits=24)),
                ('interest', models.DecimalField(decimal_places=3, max_digits=24)),
                ('total', models.DecimalField(decimal_places=3, max_digits=24)),
                ('remaining_principal', models.DecimalField(decimal_places=3, max_digits=24)),
                ('bucket', models.CharField(max_length=64)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='cashflows.calculationrun')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='calculationrun',
            constraint=models.UniqueConstraint(fields=('owner', 'idempotency_key'), name='unique_user_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='calculationrun',
            constraint=models.CheckConstraint(condition=models.Q(('progress__lte', 100)), name='progress_lte_100'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['run', 'contract_id'], name='flow_run_contract_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['run', 'currency', 'payment_date'], name='flow_run_currency_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashflow',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='unique_run_flow_sequence'),
        ),
    ]
