# Generated by Django 5.2.17 on 2026-09-16 08:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('country', models.CharField(default='Jordan', max_length=80)),
                ('base_currency', models.CharField(default='JOD', max_length=3)),
                ('is_mock', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='calculationrun',
            name='entity',
            field=models.CharField(help_text='Entity code captured at submission', max_length=64),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='entity_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='cashflows.entity'),
        ),
        migrations.CreateModel(
            name='EntityConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('bucket_days', models.JSONField(default=list)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='cashflows.entity')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('terms', models.JSONField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_contracts', to='cashflows.entity')),
            ],
            options={
                'ordering': ['external_id'],
                'constraints': [models.UniqueConstraint(fields=('entity', 'external_id'), name='unique_entity_contract')],
            },
        ),
    ]
