# Generated by Django 5.2.16 on 2026-09-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflows', '0013_regulatory_lcr_nsfr'),
        ('cashflows', '0015_behavioural_engine_extensions'),
    ]

    operations = [
    ]
