import {useEffect,useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {useQueryClient} from '@tanstack/react-query';
import {Box,Card,Stack,Typography,Button,Stepper,Step,StepLabel,TextField,Chip,Alert,Checkbox,FormControlLabel,LinearProgress,Divider,Switch,ToggleButton,ToggleButtonGroup} from '@mui/material';
import {ArrowBackRounded,ArrowForwardRounded,PlayArrowRounded,CheckCircleOutlineRounded} from '@mui/icons-material';
import {useWorkspace,usePortfolio} from '../context';
import {api,dateLabel,toInput} from '../api';
import type {Validation,Input} from '../types';
import {PageHeading,Loading,ErrorMessage,Exceptions} from '../components/Common';
export default function NewCalculation(){
 const {entity,session}=useWorkspace(),portfolio=usePortfolio(),nav=useNavigate(),client=useQueryClient();const [step,setStep]=useState(0),[asof,setAsof]=useState(''),[boundaries,setBoundaries]=useState(''),[validation,setValidation]=useState<Validation|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[accept,setAccept]=useState(false),[saveDefaults,setDefaults]=useState(false),[basis,setBasis]=useState<'contractual'|'behavioral'>('behavioral');const key=useRef(crypto.randomUUID());
 useEffect(()=>{if(portfolio.data){setAsof(portfolio.data.as_of_date);setBoundaries(portfolio.data.bucket_days.join(', '));}},[portfolio.data]);
 if(portfolio.isLoading)return <Loading/>;
 const p=portfolio.data;if(!p)return <ErrorMessage error={portfolio.error}/>;
 const makeInput=():Input=>{const days=boundaries.split(',').map(x=>Number(x.trim()));if(!asof)throw Error('Choose a reporting date.');if(days.some((x,i)=>!Number.isInteger(x)||x<1||(i>0&&x<=days[i-1])))throw Error('Use positive, increasing day boundaries with no duplicates.');return {...toInput(p),as_of_date:asof,bucket_days:days,calculation_basis:basis};};
 const validate=async()=>{setBusy(true);setError('');try{const data=await api.validate(makeInput());setValidation(data);setAccept(false);setStep(1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const run=async()=>{setBusy(true);setError('');try{const input=makeInput();if(saveDefaults&&session?.is_staff){const saved=await api.savePortfolio(input,p.revision);client.setQueryData(['portfolio',entity!.slug],saved);client.invalidateQueries({queryKey:['entities']});}const job=await api.submit(input,key.current);client.invalidateQueries({queryKey:['runs',entity!.slug]});nav(`/results/${job.id}`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <><PageHeading title="New calculation" subtitle="A guided path from saved contracts to a reproducible liquidity profile."/><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'minmax(0,1fr) 290px'},gap:3}}><Card><Box sx={{p:{xs:2,md:4}}}><Stepper activeStep={step} alternativeLabel sx={{mb:4}}>{['Configure','Validate','Calculate'].map(s=><Step key={s}><StepLabel>{s}</StepLabel></Step>)}</Stepper><ErrorMessage error={error}/>{busy&&<LinearProgress sx={{mb:3}}/>}
 {step===0&&<><Typography variant="h5">Set the calculation basis</Typography><Typography variant="body2" color="text.secondary" mt={1} mb={2}>Your saved portfolio supplies the contract terms. The contractual ladder follows the bank-approved fixed reporting buckets.</Typography><Box sx={{p:2,border:'1px solid',borderColor:'divider',borderRadius:2,bgcolor:'#F8FAFC',mb:3}}><Typography variant="subtitle2" mb={1}>Liquidity view</Typography><ToggleButtonGroup exclusive value={basis} onChange={(_,value)=>value&&setBasis(value)} size="small"><ToggleButton value="contractual">Contractual only</ToggleButton><ToggleButton value="behavioral">Behavioural</ToggleButton></ToggleButtonGroup><Typography variant="caption" display="block" color="text.secondary" mt={1}>{basis==='behavioral'?'Runs the behavioural cash-flow engine using the active runoff, prepayment, early-withdrawal, rollover and security assumptions; results remain comparable with contractual.':'Uses only contractual payment dates and balances.'}</Typography></Box><Stack gap={3}><TextField label="Reporting date" type="date" value={asof} onChange={e=>{setAsof(e.target.value);key.current=crypto.randomUUID();}} slotProps={{inputLabel:{shrink:true}}} helperText="Only payments strictly after this date are generated."/><Box sx={{p:2.25,border:'1px solid',borderColor:'divider',borderRadius:2,bgcolor:'#F8FAFC'}}><Typography variant="subtitle2">Bank reporting buckets</Typography><Typography variant="body2" color="text.secondary" mt={.5}>Open maturity · Overnight · 1w · 2w · 3w · 1m · 2m · 3m · 4m · 5m · 6m · 9m · 1y · 2y · 3y · 4y · 5y · &gt;5y</Typography></Box><Alert severity="info">Floating-rate interest follows the entity setting: current rate held constant or the saved market forward curve. Behavioural assumptions are maintained in the Behavioural Cash-Flow Engine. V1 changes principal timing; contractual interest is retained for transparency.</Alert>{session?.is_staff&&<FormControlLabel control={<Switch checked={saveDefaults} onChange={e=>setDefaults(e.target.checked)}/>} label={<Box><Typography variant="body2">Save reporting date as entity default</Typography><Typography variant="caption" color="text.secondary">Existing run snapshots are never changed.</Typography></Box>}/>}</Stack></>}
 {step===1&&validation&&<><Stack direction="row" alignItems="center" gap={1.5} mb={2}><CheckCircleOutlineRounded color={validation.rejected_count?'warning':'success'}/><Typography variant="h5">Review data readiness</Typography></Stack><Box sx={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:2,mb:3}}>{[['Accepted',validation.accepted_count],['Excluded',validation.rejected_count],['Payments',validation.cashflow_count]].map(([label,value])=><Box key={label} sx={{p:2,bgcolor:'#F6F8FB',borderRadius:2}}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h5" mt={.5}>{Number(value).toLocaleString()}</Typography></Box>)}</Box><Exceptions validation={validation}/>{validation.undated.length>0&&<Alert severity="info" sx={{mt:2}}>{validation.undated.length} open-maturity balance(s) will be disclosed separately, outside dated cash flows.</Alert>}{validation.rejected_count>0&&<FormControlLabel sx={{mt:2}} control={<Checkbox checked={accept} onChange={e=>setAccept(e.target.checked)}/>} label={<Typography variant="body2">I understand that excluded contracts make this a partial portfolio result.</Typography>}/>}</>}
 {step===2&&validation&&<><Typography variant="h5">Ready to generate cash flows</Typography><Typography variant="body2" color="text.secondary" mt={1} mb={3}>The run will retain an input snapshot, calculation settings and engine version so its results can be reproduced.</Typography><Box sx={{border:'1px solid',borderColor:'divider',borderRadius:2,p:3}}>{[['Entity',entity!.name],['Reporting date',dateLabel(asof)],['Accepted contracts',validation.accepted_count],['Excluded contracts',validation.rejected_count],['Expected payments',validation.cashflow_count.toLocaleString()],['Calculation basis',basis==='behavioral'?'Behavioural cash-flow engine · active assumptions':'Contractual only']].map(([label,value])=><Stack key={label} direction="row" justifyContent="space-between" mb={1.5} gap={2}><Typography variant="body2" color="text.secondary">{label}</Typography><Typography variant="body2" fontWeight={600}>{value}</Typography></Stack>)}</Box><Alert severity="info" sx={{mt:3}}>Calculation runs in the background. You can follow its progress on the results screen.</Alert></>}
 </Box><Divider/><Stack direction="row" justifyContent="space-between" p={2.5}><Button disabled={busy} startIcon={<ArrowBackRounded/>} onClick={()=>step?setStep(step-1):nav('/portfolio')}>{step?'Back':'Portfolio'}</Button>{step===0?<Button variant="contained" disabled={busy||!p.contracts.length} endIcon={<ArrowForwardRounded/>} onClick={validate}>{busy?'Validating…':'Validate portfolio'}</Button>:step===1?<Button variant="contained" endIcon={<ArrowForwardRounded/>} disabled={!validation?.accepted_count||(!!validation?.rejected_count&&!accept)||busy} onClick={()=>setStep(2)}>Continue</Button>:<Button variant="contained" disabled={busy} startIcon={<PlayArrowRounded/>} onClick={run}>{busy?'Submitting…':'Run calculation'}</Button>}</Stack></Card>
 <Stack gap={2}><Card sx={{p:3}}><Typography variant="overline" sx={{fontSize:9,letterSpacing:1.5,color:'text.secondary'}}>SELECTED PORTFOLIO</Typography><Typography variant="h6" mt={1}>{entity?.name}</Typography>{entity?.is_mock&&<Chip label="Mock data" size="small" sx={{my:1,bgcolor:'#FFF0D6',color:'#9D712E'}}/>}<Typography variant="h4" mt={2}>{p.contracts.length}<Typography component="span" variant="body2" color="text.secondary" ml={1}>contracts</Typography></Typography><Typography variant="body2" color="text.secondary" mt={1}>{[...new Set(p.contracts.map(c=>c.currency))].join(' · ')||'No currencies yet'}</Typography><Divider sx={{my:2}}/><Typography variant="caption" color="text.secondary">Portfolio revision {p.revision}. To change terms, return to Portfolio before validating.</Typography></Card><Box sx={{p:2.5,borderRadius:2,bgcolor:'#EBF1FD'}}><Typography variant="subtitle2">Two views, one portfolio</Typography><Typography variant="body2" color="text.secondary" mt={1}>Contractual schedules remain untouched. Behavioural runs create a separate, auditable cash-flow view from approved assumptions.</Typography></Box></Stack></Box></>;
}
