import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {useNavigate} from 'react-router-dom';
import {Box,Card,Stack,Typography,Button,Chip,Select,MenuItem,Divider,LinearProgress} from '@mui/material';
import {AddRounded,ArrowForwardRounded,SouthWestRounded,NorthEastRounded,AccountBalanceWalletOutlined,ReceiptLongOutlined,CheckCircleOutlineRounded,PlayArrowRounded} from '@mui/icons-material';
import {useWorkspace,usePortfolio,useRuns} from '../context';
import {api,compact,money,dateLabel} from '../api';
import {PageHeading,SectionHead,Loading,ErrorMessage,RunTable,Empty} from '../components/Common';
import ProfileChart from '../components/ProfileChart';
export default function Overview(){
 const {entity}=useWorkspace(),portfolio=usePortfolio(),runs=useRuns(),nav=useNavigate();const [chosenCurrency,setCurrency]=useState('');const lcr=useQuery({queryKey:['overview-lcr',entity?.slug],queryFn:()=>api.lcrReport(entity!.slug),enabled:!!entity});const nsfr=useQuery({queryKey:['overview-nsfr',entity?.slug],queryFn:()=>api.nsfrReport(entity!.slug),enabled:!!entity});
 const latest=runs.data?.runs.find(r=>['completed','completed_with_exceptions'].includes(r.status));
 const detail=useQuery({queryKey:['run',latest?.id],queryFn:()=>api.run(latest!.id),enabled:!!latest});
 if(portfolio.isLoading||runs.isLoading||detail.isLoading||lcr.isLoading||nsfr.isLoading)return <Loading/>;
 const r=detail.data?.result,currency=r?.currencies.includes(chosenCurrency)?chosenCurrency:(r?.currencies.includes(entity?.base_currency||'')?entity!.base_currency:r?.currencies[0])||entity?.base_currency||'JOD';
 const rows=r?.summary[currency]||[],inflow=rows.reduce((s,x)=>s+Number(x.inflows),0),outflow=rows.reduce((s,x)=>s+Number(x.outflows),0),net=inflow-outflow;
 const tiles=[{label:'Contractual inflows',value:compact(inflow),full:money(inflow,currency),note:'Principal + interest',color:'#178876',icon:SouthWestRounded},{label:'Contractual outflows',value:compact(outflow),full:money(outflow,currency),note:'Dated obligations',color:'#5674B9',icon:NorthEastRounded},{label:'Cumulative gap',value:compact(net),full:money(net,currency),note:'Full contractual horizon',color:net<0?'#C05257':'#168876',icon:AccountBalanceWalletOutlined},{label:'Generated payments',value:r?.cashflow_count.toLocaleString()||'0',full:'',note:'All currencies · all accepted contracts',color:'#977247',icon:ReceiptLongOutlined}];
 const regulatoryTiles=[{label:'LCR',value:lcr.data?`${(Number(lcr.data.lcr)*100).toFixed(1)}%`:'—',note:'Liquidity Coverage Ratio',color:Number(lcr.data?.lcr||0)>=1?'#178876':'#C05257',path:'/lcr'},{label:'HQLA',value:lcr.data?compact(lcr.data.hqla):'—',note:'High-quality liquid assets',color:'#178876',path:'/lcr'},{label:'NSFR',value:nsfr.data?`${(Number(nsfr.data.nsfr)*100).toFixed(1)}%`:'—',note:'Net Stable Funding Ratio',color:Number(nsfr.data?.nsfr||0)>=1?'#5674B9':'#C05257',path:'/nsfr'},{label:'Required stable funding',value:nsfr.data?compact(nsfr.data.rsf):'—',note:'Weighted RSF',color:'#977247',path:'/nsfr'}];
 return <><PageHeading title="Liquidity overview" subtitle="Executive liquidity signals, regulatory ratios and contractual cash-flow position." action={<Button variant="contained" startIcon={<AddRounded/>} onClick={()=>nav('/new')}>New calculation</Button>}/><ErrorMessage error={portfolio.error||runs.error||detail.error||lcr.error||nsfr.error}/>
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr 1fr',xl:'repeat(4,1fr)'},gap:2,mb:3}}>{regulatoryTiles.map(tile=><Card key={tile.label} onClick={()=>nav(tile.path)} sx={{p:2.5,cursor:'pointer','&:hover':{borderColor:'primary.main',transform:'translateY(-1px)'}}}><Typography sx={{fontSize:11.5,color:'text.secondary',fontWeight:500}}>{tile.label}</Typography><Stack direction="row" alignItems="baseline" gap={.8} mt={1.5}><Typography sx={{fontSize:{xs:25,md:32},fontWeight:620,letterSpacing:-1,color:tile.color}}>{tile.value}</Typography>{tile.label!=='LCR'&&tile.label!=='NSFR'&&<Typography sx={{fontSize:10,color:'text.secondary'}}>{entity?.base_currency}</Typography>}</Stack><Typography variant="caption" color="text.secondary">{tile.note}</Typography></Card>)}</Box>
 <Box sx={{display:'flex',flexWrap:'wrap',gap:2,alignItems:'center',justifyContent:'space-between',mb:2.5}}><Stack direction="row" alignItems="center" gap={1}><Typography variant="body2" fontWeight={600}>{entity?.name}</Typography><Box sx={{width:3,height:3,bgcolor:'#BBC6D2',borderRadius:'50%'}}/><Typography variant="body2" color="text.secondary">As of {dateLabel(r?.as_of_date||portfolio.data?.as_of_date||'')}</Typography>{r&&<Chip label="Latest completed run" size="small" sx={{bgcolor:'#E8F4EE',color:'#278266',display:{xs:'none',md:'flex'}}}/>}</Stack><Select size="small" value={currency} onChange={e=>setCurrency(e.target.value)} inputProps={{'aria-label':'Report currency'}} sx={{fontSize:12,minWidth:150}}>{(r?.currencies.length?r.currencies:[currency]).map(c=><MenuItem key={c} value={c}>{c} · Original currency</MenuItem>)}</Select></Box>
 {!r?<Empty title="Your portfolio is ready for its first calculation" description={`${portfolio.data?.contracts.length||0} contracts are saved for ${entity?.name}. Configure a reporting date, validate the data, and generate the first maturity profile.`} action={<Button variant="contained" startIcon={<PlayArrowRounded/>} onClick={()=>nav('/new')}>Start calculation</Button>}/>:<><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr 1fr',xl:'repeat(4,1fr)'},gap:2,mb:3}}>{tiles.map(({label,value,full,note,color,icon:Icon},i)=><Card key={label} sx={{p:2.5,minWidth:0}}><Stack direction="row" alignItems="center" justifyContent="space-between"><Typography sx={{fontSize:11.5,color:'text.secondary',fontWeight:500}}>{label}</Typography><Box sx={{display:'flex',p:.8,bgcolor:color+'0D',borderRadius:1.5,color}}><Icon sx={{fontSize:17}}/></Box></Stack><Stack direction="row" alignItems="baseline" gap={.8} mt={1.5}><Typography title={full} sx={{fontSize:{xs:25,md:32},fontWeight:620,letterSpacing:-1,color:i===2?color:'text.primary'}}>{value}</Typography>{i<3&&<Typography sx={{fontSize:10,color:'text.secondary'}}>{currency}</Typography>}</Stack><Typography variant="caption" color="text.secondary">{note}</Typography></Card>)}</Box>
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',xl:'minmax(0,2.65fr) minmax(250px,1fr)'},gap:3,mb:3}}><Card><SectionHead title="Cash-flow profile" subtitle="Contractual payment dates grouped into maturity buckets" action={<Button size="small" onClick={()=>nav(`/results/${latest!.id}`)}>Explore results <ArrowForwardRounded sx={{ml:.6,fontSize:16}}/></Button>}/><ProfileChart rows={rows} currency={currency} boundaries={r.bucket_days}/><Box sx={{px:3,py:1.5,bgcolor:'#FAFBFD',borderTop:'1px solid',borderColor:'divider'}}><Typography variant="caption" color="text.secondary">Cumulative gap excludes opening cash and undated balances. It is not a cash balance forecast.</Typography></Box></Card>
 <Card sx={{display:'flex',flexDirection:'column'}}><SectionHead title="Run quality" subtitle="Coverage and reconciliation"/><Box sx={{px:2.5,pb:2.5,flex:1}}><Box sx={{display:'inline-flex',p:1.2,bgcolor:r.rejected_count?'#FFF2DD':'#E6F5EF',borderRadius:2,mb:1.5}}><CheckCircleOutlineRounded sx={{color:r.rejected_count?'#B77B2F':'#229778',fontSize:29}}/></Box><Typography variant="h5">{!r.controls.every(c=>c.passed)?'Reconciliation mismatch':r.rejected_count?'Review exclusions':'Principal reconciles'}</Typography><Typography variant="body2" color="text.secondary" mt={1}>{r.controls.every(c=>c.passed)?'Accepted dated balances match generated principal repayments.':'One or more currencies failed principal reconciliation. Review the controls.'}</Typography><LinearProgress variant="determinate" value={r.input_count?100*r.accepted_count/r.input_count:0} sx={{my:2.5,height:5,borderRadius:5,bgcolor:'#EDF2F5','& .MuiLinearProgress-bar':{bgcolor:'#32A68B'}}}/>{[['Accepted contracts',r.accepted_count],['Excluded contracts',r.rejected_count],['Undated balances',r.undated.length]].map(([label,v])=><Stack direction="row" key={label} justifyContent="space-between" mb={1.3}><Typography variant="body2" color="text.secondary">{label}</Typography><Typography variant="body2" fontWeight={650}>{v}</Typography></Stack>)}</Box><Divider/><Button onClick={()=>nav(`/results/${latest!.id}?tab=controls`)} endIcon={<ArrowForwardRounded/>} sx={{m:1}}>View validation & controls</Button></Card></Box></>}
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',xl:'minmax(0,2.65fr) minmax(250px,1fr)'},gap:3,mt:3}}><Card><SectionHead title="Recent calculations" subtitle="Reproducible runs with saved input snapshots" action={<Button size="small" onClick={()=>nav('/runs')}>View all</Button>}/>{runs.data?.runs.length?<RunTable runs={runs.data.runs} limit={4}/>:<Box p={3}><Typography color="text.secondary" variant="body2">No calculations yet.</Typography></Box>}</Card><Card sx={{p:2.5,bgcolor:'#F0F4FE',borderColor:'#DCE6FA'}}><Typography variant="h6">Your next analysis</Typography><Typography variant="body2" color="text.secondary" mt={1} mb={2}>Adjust a contract, compare a new run, or inspect the timing of principal and interest.</Typography><Button variant="outlined" sx={{bgcolor:'white'}} endIcon={<ArrowForwardRounded/>} onClick={()=>nav('/portfolio')}>Review portfolio</Button><Divider sx={{my:2}}><Chip label="CONTRACTUAL BASELINE" size="small" sx={{fontSize:8,bgcolor:'#E4EBFC',color:'#6580B6'}}/></Divider><Typography variant="caption" color="text.secondary">No deposit runoff, prepayments or rollovers are assumed.</Typography></Card></Box></>;
}
