import {useEffect,useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {useQueryClient} from '@tanstack/react-query';
import {Box,Card,Stack,Typography,Button,TextField,InputAdornment,Chip,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TablePagination,IconButton,Tooltip,Alert,MenuItem,Dialog,DialogTitle,DialogContent,DialogActions} from '@mui/material';
import {SearchRounded,AddRounded,EditOutlined,DeleteOutlineRounded,SaveOutlined,UploadFileRounded,ArrowForwardRounded,DownloadOutlined} from '@mui/icons-material';
import {useWorkspace,usePortfolio} from '../context';
import {api,money,productLabel,toInput} from '../api';
import type {Contract,Input} from '../types';
import {PageHeading,Loading,ErrorMessage} from '../components/Common';
import ContractEditor from '../components/ContractEditor';
export default function PortfolioPage(){
 const {entity,session}=useWorkspace(),query=usePortfolio(),client=useQueryClient(),nav=useNavigate();const [draft,setDraft]=useState<Contract[]>([]),[dirty,setDirty]=useState(false),[search,setSearch]=useState(''),[currency,setCurrency]=useState('All'),[page,setPage]=useState(0),[edit,setEdit]=useState<{value:Contract;index:number}|null>(null),[remove,setRemove]=useState<number|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(query.data&&!dirty)setDraft(query.data.contracts);},[query.data,dirty]);
 useEffect(()=>{setPage(0)},[search,currency]);
 if(query.isLoading)return <Loading/>;
 const filtered=draft.map((c,i)=>({c,i})).filter(({c})=>(currency==='All'||c.currency===currency)&&(c.contract_id.toLowerCase().includes(search.toLowerCase())||productLabel(c.product).toLowerCase().includes(search.toLowerCase())));
 const save=async()=>{if(!query.data)return;setSaving(true);setError('');try{const data=await api.savePortfolio({...toInput(query.data),contracts:draft},query.data.revision);client.setQueryData(['portfolio',entity!.slug],data);setDirty(false);setNotice('Portfolio saved. Existing calculation snapshots remain unchanged.');client.invalidateQueries({queryKey:['entities']});}catch(e){setError((e as Error).message);}finally{setSaving(false);}};
 const download=()=>{if(!query.data)return;const url=URL.createObjectURL(new Blob([JSON.stringify({...toInput(query.data),contracts:draft},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${entity!.slug}-portfolio.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>4*1024*1024)throw Error('Maximum JSON file size is 4 MB.');const input=JSON.parse(await f.text()) as Input;if(!Array.isArray(input.contracts)||!input.contracts.length)throw Error('Expected a JSON object with a nonempty contracts array.');if(input.entity!==entity!.slug)throw Error(`File entity must be ${entity!.slug}. Update it explicitly before importing.`);if(input.contracts.some(c=>!c||typeof c.contract_id!=='string'||typeof c.product!=='string'||typeof c.currency!=='string'||!Number.isFinite(Number(c.principal))||Number(c.principal)<=0))throw Error('Every contract needs contract_id, product, currency and a positive principal.');setDraft(input.contracts);setDirty(true);setNotice('Contract terms imported into an unsaved draft. Reporting settings remain unchanged.');}catch(x){setError((x as Error).message);}finally{e.target.value='';}};
 return <><PageHeading title="Portfolio" subtitle={`Saved contract terms for ${entity?.name}. Changes affect future runs only.`} action={<Stack direction="row" gap={1}><Button variant="outlined" endIcon={<ArrowForwardRounded/>} disabled={dirty||!draft.length} onClick={()=>nav('/new')}>New calculation</Button>{session?.is_staff&&<Button variant="contained" startIcon={<SaveOutlined/>} disabled={!dirty||saving||!draft.length} onClick={save}>{saving?'Saving…':'Save portfolio'}</Button>}</Stack>}/><ErrorMessage error={error||query.error}/>{notice&&<Alert severity="success" onClose={()=>setNotice('')} sx={{mb:2}}>{notice}</Alert>}{dirty&&<Alert severity="warning" sx={{mb:2}} action={<Button color="inherit" size="small" onClick={()=>{setDirty(false);setDraft(query.data!.contracts);}}>Discard</Button>}>You have unsaved changes. Save this portfolio before starting a calculation.</Alert>}
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(3,1fr)'},gap:2,mb:3}}>{[['Saved / draft contracts',draft.length],['Product types',new Set(draft.map(c=>c.product)).size],['Currencies',Array.from(new Set(draft.map(c=>c.currency))).join(' · ')||'—']].map(([label,value])=><Card key={label} sx={{p:2.5}}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h5" mt={.5}>{value}</Typography></Card>)}</Box>
 <Card><Stack direction={{xs:'column',md:'row'}} p={2.5} gap={1.5} alignItems={{xs:'stretch',md:'center'}}><TextField placeholder="Search contracts or products" size="small" value={search} onChange={e=>setSearch(e.target.value)} sx={{minWidth:240}} slotProps={{input:{startAdornment:<InputAdornment position="start"><SearchRounded fontSize="small"/></InputAdornment>}}}/><TextField label="Currency" select size="small" value={currency} onChange={e=>setCurrency(e.target.value)} sx={{minWidth:120}}>{['All',...new Set(draft.map(c=>c.currency))].map(c=><MenuItem key={c} value={c}>{c}</MenuItem>)}</TextField><Box sx={{flex:1}}/><Tooltip title="Download portfolio JSON"><IconButton aria-label="Download portfolio" onClick={download}><DownloadOutlined/></IconButton></Tooltip>{session?.is_staff&&<><Button startIcon={<UploadFileRounded/>} onClick={()=>file.current?.click()}>Import JSON</Button><input ref={file} type="file" accept="application/json,.json" style={{display:'none'}} onChange={upload}/><Button variant="outlined" startIcon={<AddRounded/>} onClick={()=>setEdit({index:-1,value:{contract_id:'',product:'loan',currency:entity?.base_currency||'JOD',principal:'',annual_rate:'0.06',rate_type:'fixed',repayment:'equal_principal',day_count:'ACT/365F',frequency_months:3,accrual_start:query.data?.as_of_date||'',next_payment:'',maturity:'',end_of_month:false}})}>Add contract</Button></>}</Stack>
 <TableContainer><Table><TableHead><TableRow><TableCell>Contract</TableCell><TableCell>Product</TableCell><TableCell>Currency</TableCell><TableCell align="right">Principal</TableCell><TableCell align="right">Rate</TableCell><TableCell>Maturity</TableCell><TableCell>Repayment</TableCell><TableCell/></TableRow></TableHead><TableBody>{filtered.slice(page*10,page*10+10).map(({c,i})=><TableRow key={`${c.contract_id}-${i}`} hover><TableCell sx={{fontWeight:600}}>{c.contract_id}</TableCell><TableCell>{productLabel(c.product)}</TableCell><TableCell><Chip label={c.currency} size="small" variant="outlined"/></TableCell><TableCell align="right" sx={{fontVariantNumeric:'tabular-nums'}}>{money(c.principal,c.currency)}</TableCell><TableCell align="right">{c.annual_rate!=null?`${(Number(c.annual_rate)*100).toFixed(2)}%`:'—'}</TableCell><TableCell sx={{whiteSpace:'nowrap'}}>{c.maturity||<Chip label="Open maturity" size="small" sx={{bgcolor:'#F1F4F8',color:'text.secondary'}}/>}</TableCell><TableCell sx={{textTransform:'capitalize'}}>{c.repayment?.replaceAll('_',' ')||'Undated'}</TableCell><TableCell sx={{whiteSpace:'nowrap'}}>{session?.is_staff&&<><Tooltip title={`Edit ${c.contract_id}`}><IconButton size="small" aria-label={`Edit ${c.contract_id}`} onClick={()=>setEdit({value:c,index:i})}><EditOutlined sx={{fontSize:17}}/></IconButton></Tooltip><Tooltip title={`Remove ${c.contract_id}`}><IconButton size="small" aria-label={`Remove ${c.contract_id}`} onClick={()=>setRemove(i)}><DeleteOutlineRounded sx={{fontSize:17}}/></IconButton></Tooltip></>}</TableCell></TableRow>)}{!filtered.length&&<TableRow><TableCell colSpan={8} align="center" sx={{py:5,color:'text.secondary'}}>No contracts match. Add or import contracts to begin.</TableCell></TableRow>}</TableBody></Table></TableContainer><TablePagination component="div" count={filtered.length} page={Math.min(page,Math.max(0,Math.ceil(filtered.length/10)-1))} onPageChange={(_,p)=>setPage(p)} rowsPerPage={10} rowsPerPageOptions={[10]}/></Card>
 <Typography variant="caption" color="text.secondary" display="block" mt={2}>Contract amounts stay in their original currency. Validate the portfolio in New calculation to check financial rules.</Typography>
 {edit&&<ContractEditor existingIds={draft.filter((_,i)=>i!==edit.index).map(c=>c.contract_id)} contract={edit.value} onClose={()=>setEdit(null)} onSave={c=>{if(draft.some((d,i)=>d.contract_id===c.contract_id&&i!==edit.index)){setError('Contract ID already exists in this entity.');return;}setDraft(d=>edit.index<0?[...d,c]:d.map((v,i)=>i===edit.index?c:v));setDirty(true);setEdit(null);}}/>}
 <Dialog open={remove!==null} onClose={()=>setRemove(null)}><DialogTitle>Remove this contract from the draft?</DialogTitle><DialogContent><Typography variant="body2">{remove!==null?draft[remove]?.contract_id:''} will be removed when you save. Existing run snapshots will remain available.</Typography></DialogContent><DialogActions><Button onClick={()=>setRemove(null)}>Cancel</Button><Button color="error" onClick={()=>{setDraft(d=>d.filter((_,i)=>i!==remove));setDirty(true);setRemove(null);}}>Remove from draft</Button></DialogActions></Dialog></>;
}
