import {useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {Alert,Box,Button,Card,Chip,InputAdornment,MenuItem,Stack,Table,TableBody,TableCell,TableContainer,TableHead,TablePagination,TableRow,TextField,Typography} from '@mui/material';
import {ArrowForwardRounded,SearchRounded,StorageRounded} from '@mui/icons-material';
import {useWorkspace} from '../context';
import {api,money,productLabel} from '../api';
import {PageHeading,Loading,ErrorMessage} from '../components/Common';

const PAGE_SIZE=50;

export default function PortfolioPage(){
 const {entity}=useWorkspace(),nav=useNavigate();
 const [query,setQuery]=useState(''),[search,setSearch]=useState(''),[currency,setCurrency]=useState(''),[product,setProduct]=useState(''),[page,setPage]=useState(0);
 const summary=useQuery({queryKey:['portfolio-summary',entity?.slug],queryFn:()=>api.portfolioSummary(entity!.slug),enabled:!!entity});
 const contracts=useQuery({queryKey:['portfolio-contracts',entity?.slug,search,currency,product,page],queryFn:()=>api.portfolioContracts(entity!.slug,{q:search||undefined,currency:currency||undefined,product:product||undefined,offset:page*PAGE_SIZE,limit:PAGE_SIZE}),enabled:!!entity,placeholderData:previous=>previous});
 useEffect(()=>{setPage(0);setSearch('');setQuery('');setCurrency('');setProduct('');},[entity?.slug]);
 useEffect(()=>{const timer=window.setTimeout(()=>{setSearch(query.trim());setPage(0);},250);return()=>window.clearTimeout(timer);},[query]);
 if(summary.isLoading)return <Loading/>;
 const p=summary.data;if(!p)return <ErrorMessage error={summary.error}/>;
 const rows=contracts.data?.contracts||[];
 return <><PageHeading title="Portfolio" subtitle={`Canonical calculation terms for ${entity?.name}. Designed for bank-scale, server-side browsing.`} action={<Button variant="contained" endIcon={<ArrowForwardRounded/>} disabled={!p.contract_count} onClick={()=>nav('/new')}>New calculation</Button>}/>
 <Alert icon={<StorageRounded fontSize="inherit"/>} severity="info" sx={{mb:3}}>The portfolio is read-only here: approved ETL mappings publish bank data into the canonical ALM structure. This protects the daily source load and keeps manual browser edits out of production data.</Alert>
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,1fr)',lg:'repeat(4,1fr)'},gap:2,mb:3}}>{[['Saved contracts',p.contract_count.toLocaleString()],['Products',p.product_count],['Currencies',p.currencies.join(' · ')||'—'],['No bank maturity',p.missing_maturity_count.toLocaleString()]].map(([label,value])=><Card key={label} sx={{p:2.5}}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h5" mt={.5}>{value}</Typography></Card>)}</Box>
 <Card><Stack direction={{xs:'column',lg:'row'}} gap={1.5} alignItems={{lg:'center'}} p={2.5}><TextField value={query} onChange={event=>setQuery(event.target.value)} size="small" label="Find a contract or product type" placeholder="e.g. JOD-LN-0001" sx={{minWidth:{lg:320}}} InputProps={{startAdornment:<InputAdornment position="start"><SearchRounded fontSize="small"/></InputAdornment>}}/><TextField select label="Currency" size="small" value={currency} onChange={event=>{setCurrency(event.target.value);setPage(0)}} sx={{minWidth:130}}><MenuItem value="">All currencies</MenuItem>{p.currencies.map(item=><MenuItem key={item} value={item}>{item}</MenuItem>)}</TextField><TextField select label="Engine product" size="small" value={product} onChange={event=>{setProduct(event.target.value);setPage(0)}} sx={{minWidth:180}}><MenuItem value="">All products</MenuItem>{p.products.map(item=><MenuItem key={item} value={item}>{productLabel(item)}</MenuItem>)}</TextField><Typography variant="caption" color="text.secondary" sx={{ml:{lg:'auto'}}}>Showing at most {PAGE_SIZE} records at a time</Typography></Stack><ErrorMessage error={contracts.error}/><TableContainer><Table><TableHead><TableRow><TableCell>Contract</TableCell><TableCell>Product</TableCell><TableCell>Product type</TableCell><TableCell>Currency</TableCell><TableCell align="right">Principal</TableCell><TableCell>Maturity</TableCell><TableCell>Source</TableCell></TableRow></TableHead><TableBody>{rows.map(contract=><TableRow key={contract.contract_id} hover><TableCell sx={{fontWeight:650}}>{contract.contract_id}</TableCell><TableCell>{productLabel(contract.product)}</TableCell><TableCell>{contract.liquidity_product?<Chip size="small" variant="outlined" color="primary" label={contract.liquidity_product.replaceAll('_',' ')}/>:<Typography variant="body2" color="text.secondary">Not mapped</Typography>}</TableCell><TableCell><Chip size="small" variant="outlined" label={contract.currency}/></TableCell><TableCell align="right" sx={{fontVariantNumeric:'tabular-nums'}}>{money(contract.principal,contract.currency)}</TableCell><TableCell>{contract.maturity||<Chip label="Open maturity" size="small" sx={{bgcolor:'#F1F4F8',color:'text.secondary'}}/>}</TableCell><TableCell><Chip size="small" label={contract.maturity?'Bank maturity':'Open / policy-controlled'} color={contract.maturity?'default':'warning'} variant="outlined"/></TableCell></TableRow>)}{!contracts.isFetching&&!rows.length&&<TableRow><TableCell colSpan={7} align="center" sx={{py:5,color:'text.secondary'}}>No contracts match these filters.</TableCell></TableRow>}</TableBody></Table></TableContainer><TablePagination component="div" count={contracts.data?.total||0} page={page} rowsPerPage={PAGE_SIZE} rowsPerPageOptions={[PAGE_SIZE]} onPageChange={(_,next)=>setPage(next)}/></Card>
 <Typography variant="caption" color="text.secondary" display="block" mt={2}>Portfolio revision {p.revision}. Daily ETL refreshes change future calculations only; each submitted run retains its own immutable contract snapshot.</Typography></>;
}
