import {useMemo,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Alert,Box,Button,Card,Chip,Dialog,DialogContent,DialogTitle,Divider,IconButton,LinearProgress,Stack,Tab,Tabs,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,Typography} from '@mui/material';
import {CalculateOutlined,CloseRounded,DownloadOutlined,FactCheckOutlined,InfoOutlined} from '@mui/icons-material';
import {api,money,dateLabel,timeLabel} from '../api';
import {useWorkspace} from '../context';
import type {RegulatoryCalculation,RegulatoryContribution,RegulatoryLine} from '../types';

const pct=(v:string|null)=>v==null?'—':`${Number(v).toLocaleString('en-US',{maximumFractionDigits:2})}%`;
function Kpi({label,value,sub}:{label:string;value:string;sub?:string}){return <Card sx={{p:2.2}}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h5" mt={.5}>{value}</Typography>{sub&&<Typography variant="caption" color="text.secondary">{sub}</Typography>}</Card>}
export default function Regulatory(){
 const {entity}=useWorkspace();const qc=useQueryClient();const [tab,setTab]=useState(0);const [selected,setSelected]=useState<RegulatoryCalculation|null>(null);const [drill,setDrill]=useState<{metric:'LCR'|'NSFR';line:RegulatoryLine}|null>(null);
 const history=useQuery({queryKey:['regulatory-calculations',entity?.slug],queryFn:()=>api.regulatoryCalculations(entity!.slug),enabled:!!entity});
 const mappings=useQuery({queryKey:['regulatory-mappings',entity?.slug],queryFn:()=>api.regulatoryMappings(entity!.slug),enabled:!!entity});
 const config=useQuery({queryKey:['regulatory-config',entity?.slug],queryFn:()=>api.regulatoryConfig(entity!.slug),enabled:!!entity});
 const calc=useMutation({mutationFn:()=>api.calculateRegulatory(entity!.slug),onSuccess:r=>{setSelected(r);qc.invalidateQueries({queryKey:['regulatory-calculations',entity?.slug]});}});
 const current=selected||history.data?.[0]||null;
 const contrib=useQuery({queryKey:['regulatory-contrib',entity?.slug,current?.id,drill?.metric,drill?.line.code],queryFn:()=>api.regulatoryContributions(entity!.slug,current!.id,drill!.metric,drill!.line.code),enabled:!!entity&&!!current&&!!drill});
 if(!entity)return null;
 if(history.isLoading||mappings.isLoading||config.isLoading)return <LinearProgress/>;
 const report=(metric:'LCR'|'NSFR',lines:RegulatoryLine[])=><TableContainer><Table size="small"><TableHead><TableRow><TableCell>Section</TableCell><TableCell>Code</TableCell><TableCell>Line item</TableCell><TableCell align="right">Source balance</TableCell><TableCell align="right">Weighted amount</TableCell></TableRow></TableHead><TableBody>{lines.map(row=><TableRow key={row.code} hover onClick={()=>setDrill({metric,line:row})} sx={{cursor:'pointer'}}><TableCell><Chip size="small" label={row.section}/></TableCell><TableCell>{row.code}</TableCell><TableCell>{row.label}</TableCell><TableCell align="right">{money(row.source_balance,current?.controls.reporting_currency)}</TableCell><TableCell align="right">{money(row.weighted_amount,current?.controls.reporting_currency)}</TableCell></TableRow>)}</TableBody></Table></TableContainer>;
 return <Stack gap={2.5}>
  <Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={2}><Box><Typography variant="h4">LCR & NSFR Engine</Typography><Typography color="text.secondary" mt={.7}>Calculates regulatory liquidity metrics directly from the saved ALM source portfolio using configurable mappings and persisted audit contributions.</Typography></Box><Stack direction="row" gap={1}><Button variant="contained" startIcon={<CalculateOutlined/>} onClick={()=>calc.mutate()} disabled={calc.isPending}>Calculate from source data</Button>{current&&<Button component="a" href={`/api/v1/entities/${entity.slug}/regulatory/calculations/${current.id}/workbook`} startIcon={<DownloadOutlined/>}>Excel workbook</Button>}</Stack></Stack>
  {calc.error&&<Alert severity="error">{String(calc.error)}</Alert>}
  <Alert severity="info" icon={<InfoOutlined/>}>This first-stage engine is deterministic and single-entity. Mapping factors are configurable and must be approved against the bank’s current regulatory methodology before production use.</Alert>
  {current?<>
   <Stack direction="row" gap={1} alignItems="center" flexWrap="wrap"><Chip label={`Report date ${dateLabel(current.as_of_date)}`}/><Chip label={`Engine ${current.engine_version}`}/><Chip label={`Methodology ${current.methodology_version||'—'}`}/><Chip color={current.controls.complete_mapping?'success':'warning'} label={current.controls.complete_mapping?'Mapping complete':'Mapping exceptions'}/><Typography variant="caption" color="text.secondary">Calculated {timeLabel(current.created)}</Typography></Stack>
   <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(4,1fr)'},gap:2}}><Kpi label="LCR" value={pct(current.lcr_result.ratio)} sub="HQLA / 30-day net cash outflows"/><Kpi label="HQLA" value={money(current.lcr_result.hqla,current.controls.reporting_currency)}/><Kpi label="NSFR" value={pct(current.nsfr_result.ratio)} sub="ASF / RSF"/><Kpi label="Mapping coverage" value={`${current.controls.mapped_contract_count}/${current.controls.source_contract_count}`} sub={`${current.controls.warning_count} warning(s)`}/></Box>
   <Card><Tabs value={tab} onChange={(_,v)=>setTab(v)}><Tab label="LCR report"/><Tab label="NSFR report"/><Tab label="Mappings"/><Tab label="Controls & warnings"/><Tab label="Run history"/></Tabs><Divider/>
    {tab===0&&<Box><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(5,1fr)'},gap:1.5,p:2}}><Kpi label="HQLA" value={money(current.lcr_result.hqla,current.controls.reporting_currency)}/><Kpi label="Gross outflows" value={money(current.lcr_result.gross_outflows,current.controls.reporting_currency)}/><Kpi label="Gross inflows" value={money(current.lcr_result.gross_inflows,current.controls.reporting_currency)}/><Kpi label="Eligible inflows" value={money(current.lcr_result.eligible_inflows,current.controls.reporting_currency)}/><Kpi label="Net cash outflows" value={money(current.lcr_result.net_cash_outflows,current.controls.reporting_currency)}/></Box><Stack direction="row" justifyContent="flex-end" px={2} pb={1}><Button component="a" href={`/api/v1/entities/${entity.slug}/regulatory/calculations/${current.id}/export/lcr`} startIcon={<DownloadOutlined/>}>Export LCR CSV</Button></Stack>{report('LCR',current.lcr_result.lines)}</Box>}
    {tab===1&&<Box><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(3,1fr)'},gap:1.5,p:2}}><Kpi label="Available stable funding" value={money(current.nsfr_result.asf,current.controls.reporting_currency)}/><Kpi label="Required stable funding" value={money(current.nsfr_result.rsf,current.controls.reporting_currency)}/><Kpi label="NSFR" value={pct(current.nsfr_result.ratio)}/></Box><Stack direction="row" justifyContent="flex-end" px={2} pb={1}><Button component="a" href={`/api/v1/entities/${entity.slug}/regulatory/calculations/${current.id}/export/nsfr`} startIcon={<DownloadOutlined/>}>Export NSFR CSV</Button></Stack>{report('NSFR',current.nsfr_result.lines)}</Box>}
    {tab===2&&<TableContainer><Table size="small"><TableHead><TableRow><TableCell>Source product</TableCell><TableCell>Liquidity group / product</TableCell><TableCell>Mapping</TableCell><TableCell>LCR treatment</TableCell><TableCell>NSFR treatment</TableCell><TableCell>Source</TableCell></TableRow></TableHead><TableBody>{mappings.data?.map(m=><TableRow key={m.id}><TableCell>{m.source_product}</TableCell><TableCell>{[m.liquidity_group,m.liquidity_product].filter(Boolean).join(" / ")||"All"}</TableCell><TableCell>{m.title}</TableCell><TableCell><Typography variant="caption" component="pre" sx={{whiteSpace:'pre-wrap',m:0}}>{JSON.stringify(m.lcr_treatment,null,2)}</Typography></TableCell><TableCell><Typography variant="caption" component="pre" sx={{whiteSpace:'pre-wrap',m:0}}>{JSON.stringify(m.nsfr_treatment,null,2)}</Typography></TableCell><TableCell><Typography variant="caption">{m.source}</Typography></TableCell></TableRow>)}</TableBody></Table></TableContainer>}
    {tab===3&&<Box p={2.5}><Stack gap={1}><Typography variant="subtitle2">Reconciliation controls</Typography><Typography variant="body2">Reporting currency: <b>{current.controls.reporting_currency}</b></Typography><Typography variant="body2">Converted source balance: <b>{money(current.controls.source_balance_converted,current.controls.reporting_currency)}</b></Typography><Typography variant="body2">Mapped balance: <b>{money(current.controls.mapped_balance_converted,current.controls.reporting_currency)}</b></Typography>{current.warnings.length===0?<Alert severity="success">No unmapped products or missing FX rates.</Alert>:current.warnings.map((w,i)=><Alert key={i} severity="warning"><b>{w.contract_id}</b> · {w.message}</Alert>)}</Stack></Box>}
    {tab===4&&<TableContainer><Table size="small"><TableHead><TableRow><TableCell>Created</TableCell><TableCell>Report date</TableCell><TableCell>LCR</TableCell><TableCell>NSFR</TableCell><TableCell>Warnings</TableCell></TableRow></TableHead><TableBody>{history.data?.map(r=><TableRow key={r.id} hover onClick={()=>setSelected(r)} sx={{cursor:'pointer'}}><TableCell>{timeLabel(r.created)}</TableCell><TableCell>{dateLabel(r.as_of_date)}</TableCell><TableCell>{pct(r.lcr_result.ratio)}</TableCell><TableCell>{pct(r.nsfr_result.ratio)}</TableCell><TableCell>{r.controls.warning_count}</TableCell></TableRow>)}</TableBody></Table></TableContainer>}
   </Card>
  </>:<Alert severity="info" icon={<FactCheckOutlined/>}>No regulatory calculation has been run yet. Click <b>Calculate from source data</b>.</Alert>}
  <Dialog open={!!drill} onClose={()=>setDrill(null)} fullWidth maxWidth="lg"><DialogTitle>{drill?.line.label}<IconButton onClick={()=>setDrill(null)} sx={{float:'right'}}><CloseRounded/></IconButton></DialogTitle><DialogContent>{contrib.isLoading?<LinearProgress/>:<TableContainer><Table size="small"><TableHead><TableRow><TableCell>Contract</TableCell><TableCell>Product</TableCell><TableCell>Currency</TableCell><TableCell>Maturity band</TableCell><TableCell align="right">Source balance</TableCell><TableCell align="right">Factor</TableCell><TableCell align="right">Contribution</TableCell></TableRow></TableHead><TableBody>{(contrib.data||[]).map((c:RegulatoryContribution,i)=><TableRow key={`${c.contract_id}-${i}`}><TableCell>{c.contract_id}</TableCell><TableCell>{c.product}</TableCell><TableCell>{c.currency}</TableCell><TableCell>{c.maturity_band}</TableCell><TableCell align="right">{money(c.source_balance,current?.controls.reporting_currency)}</TableCell><TableCell align="right">{(Number(c.factor)*100).toFixed(2)}%</TableCell><TableCell align="right">{money(c.weighted_amount,current?.controls.reporting_currency)}</TableCell></TableRow>)}</TableBody></Table></TableContainer>}</DialogContent></Dialog>
 </Stack>
}
