import {useEffect,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Alert,Box,Button,Card,IconButton,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,ToggleButton,ToggleButtonGroup,Typography} from '@mui/material';
import {AddRounded,DeleteOutlineRounded,SaveRounded} from '@mui/icons-material';
import {useWorkspace} from '../context'; import {api} from '../api'; import type {ForwardCurvePoint} from '../types'; import {ErrorMessage,Loading,PageHeading,SectionHead} from '../components/Common';
const blank=():ForwardCurvePoint=>({currency:'JOD',index:'JOD-3M',tenor_days:90,rate:'0.060000'});
export default function Settings(){
 const {entity,session}=useWorkspace(),client=useQueryClient(); const query=useQuery({queryKey:['settings',entity?.slug],queryFn:()=>api.settings(entity!.slug),enabled:!!entity});
 const [projection,setProjection]=useState<'constant'|'forward_curve'>('constant'),[curve,setCurve]=useState<ForwardCurvePoint[]>([]),[message,setMessage]=useState('');
 useEffect(()=>{if(query.data){setProjection(query.data.interest_projection);setCurve(query.data.forward_curve)}},[query.data]);
 if(query.isLoading)return <Loading/>; if(query.error||!entity)return <ErrorMessage error={query.error}/>;
 const edit=(i:number,key:keyof ForwardCurvePoint,value:string)=>setCurve(curve.map((p,n)=>n===i?{...p,[key]:key==='tenor_days'?Number(value):value}:p));
 const save=async()=>{setMessage('');try{await api.saveSettings(entity.slug,{interest_projection:projection,forward_curve:curve});client.invalidateQueries({queryKey:['settings',entity.slug]});setMessage('Interest projection settings saved. Every new calculation will snapshot them.')}catch(e){setMessage((e as Error).message)}};
 return <><PageHeading title="Interest projection settings" subtitle="A contractual market-rate convention for floating-rate instruments — not a behavioural assumption."/>
 <Card sx={{maxWidth:1050,mb:3}}><Box sx={{p:{xs:2.5,md:4}}}><Typography variant="h6">Future floating-rate interest</Typography><Typography variant="body2" color="text.secondary" mt={.75} mb={3}>Fixed-rate contracts always use their contractual rate. Choose how future interest is projected for floating-rate contracts.</Typography>
 <ToggleButtonGroup exclusive value={projection} onChange={(_,v)=>v&&setProjection(v)} fullWidth sx={{'& .MuiToggleButton-root':{py:2,textTransform:'none',justifyContent:'flex-start,',textAlign:'left'}}}><ToggleButton value="constant"><Box><Typography fontWeight={650}>Hold rate constant</Typography><Typography variant="caption">Use each contract’s current all-in rate through maturity.</Typography></Box></ToggleButton><ToggleButton value="forward_curve"><Box><Typography fontWeight={650}>Use market forward curve</Typography><Typography variant="caption">Use forward index rate + contractual margin, then apply any cap or floor.</Typography></Box></ToggleButton></ToggleButtonGroup>
 {projection==='constant'&&<Alert severity="info" sx={{mt:3}}>This is the initial default. It does not make any prepayment, runoff, or withdrawal assumptions.</Alert>}</Box></Card>
 {projection==='forward_curve'&&<Card sx={{maxWidth:1200}}><SectionHead title="Market forward curve" subtitle="Enter approved curve points manually for this prototype. CSV/Excel upload can be added when the bank source is confirmed." action={<Button startIcon={<AddRounded/>} onClick={()=>setCurve([...curve,blank()])}>Add point</Button>}/><Table><TableHead><TableRow><TableCell>Currency</TableCell><TableCell>Rate index</TableCell><TableCell>Tenor (days)</TableCell><TableCell>Forward rate (decimal)</TableCell><TableCell/></TableRow></TableHead><TableBody>{curve.map((p,i)=><TableRow key={i}><TableCell><TextField size="small" value={p.currency} onChange={e=>edit(i,'currency',e.target.value)} sx={{width:90}}/></TableCell><TableCell><TextField size="small" value={p.index} onChange={e=>edit(i,'index',e.target.value)}/></TableCell><TableCell><TextField size="small" type="number" value={p.tenor_days} onChange={e=>edit(i,'tenor_days',e.target.value)}/></TableCell><TableCell><TextField size="small" value={p.rate} onChange={e=>edit(i,'rate',e.target.value)} helperText="0.060000 = 6%"/></TableCell><TableCell><IconButton aria-label="Remove curve point" onClick={()=>setCurve(curve.filter((_,n)=>n!==i))}><DeleteOutlineRounded/></IconButton></TableCell></TableRow>)}{!curve.length&&<TableRow><TableCell colSpan={5}><Alert severity="warning">Add at least one curve point to use the market forward-curve method.</Alert></TableCell></TableRow>}</TableBody></Table></Card>}
 <Stack direction="row" justifyContent="flex-end" mt={3} maxWidth={1200}><Button variant="contained" disabled={!session?.is_staff} startIcon={<SaveRounded/>} onClick={save}>Save settings</Button></Stack>{!session?.is_staff&&<Alert severity="info" sx={{mt:2,maxWidth:1200}}>You can view these settings; an administrator can change them.</Alert>}{message&&<Alert severity={message.startsWith('Interest')?'success':'error'} sx={{mt:2,maxWidth:1200}}>{message}</Alert>}</>;
}
